# Generated by Django 5.0.6 on 2024-05-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'formulario de contacto',
                'verbose_name_plural': 'formularios de contacto',
            },
        ),
    ]
