# Generated by Django 5.0.6 on 2024-05-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='coaches',
            field=models.ManyToManyField(related_name='services', to='user.coach', verbose_name='entrenadores'),
        ),
        migrations.AddField(
            model_name='services',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=8, verbose_name='precio'),
            preserve_default=False,
        ),
    ]
