# Generated by Django 5.0.6 on 2024-05-23 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_services_coaches_services_price'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='coaches',
        ),
        migrations.AddField(
            model_name='services',
            name='coach',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.coach', verbose_name='entrenador'),
        ),
    ]
