# Generated by Django 5.0.6 on 2024-05-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_services_coaches_services_coach'),
        ('user', '0002_alter_coach_options_alter_customer_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='coach',
        ),
        migrations.AddField(
            model_name='services',
            name='coach',
            field=models.ManyToManyField(to='user.coach', verbose_name='entrenador'),
        ),
    ]
