# Generated by Django 5.0.6 on 2024-05-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True, verbose_name='clave')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('url', models.URLField(blank=True, null=True, verbose_name='enlace')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated', models.DateField(auto_now=True, verbose_name='Fecha de modificacion')),
            ],
            options={
                'verbose_name': 'enlace',
                'verbose_name_plural': 'enlaces',
            },
        ),
    ]
