# Generated by Django 5.0.6 on 2024-05-23 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name': 'entrenador', 'verbose_name_plural': 'entrenadores'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
    ]
